let karel = "abc";
let water = 20;
let cat = 5;
let phone = "headphones";
let tshirt = "pants";
const socks = "tshirt";
const dog = "karel";
const boat = "water";
const mouse = "cat";
const charger = "phone";
console.log(karel);
console.log(water);
console.log(cat);
console.log(phone);
console.log(tshirt);
console.log(socks);
console.log(dog);
console.log(boat);
console.log(mouse);
console.log(charger);
